[metadata]
name = concert_isaac
version = 1.0.0
author = IIT
description = Python package to simulate the IIT Concert robot in Isaac Lab.
license = MIT

[options]
package_dir =
    = src
packages = find_namespace:
include_package_data = True
python_requires = >=3.10

[options.packages.find]
where = src
