context:
  session: concert_real
  params:
    hw_type: ec_idle
  .defines:

    - &embedded embedded@10.24.10.100
    - &control concert@10.24.10.102
    - &vision concert@10.24.10.101
    - &docker-xeno concert-focal-ros1-xeno-dev-1
    - &docker-dev concert-focal-ros1-dev-1

ecat:
  cmd: ecat_master
  machine: *embedded
  docker: *docker-xeno
  
xbot2:
  cmd: xbot2-core --hw {hw_type}
  machine: *embedded
  ready_check: timeout 5 rostopic echo /xbotcore/joint_states -n 1
  depends: []
  docker: *docker-xeno
  variants:
    verbose:
      cmd: "{cmd} -V"
    ctrl:
      - ec_idle:
          params:
            hw_type: ec_idle
      - ec_pos:
          params:
            hw_type: ec_pos
      - ec_imp:
          params:
            hw_type: ec_imp
      - dummy:
          params:
            hw_type: dummy
